### ISSUE TITLE
RServe client gem is not being updated

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-server#763]
RServe-Client is not working with Ruby 3.2.2 and is not being developed anymore!

`/opt/openstudio/server/app/lib/analysis_library/lhs.rb failed with uninitialized constant Rserve::REXP::Wrapper::Fixnum, /usr/local/lib/ruby/gems/3.2.0/gems/rserve-client-0.3.5/lib/rserve/rexp/wrapper.rb:26:in 'wrap'
/usr/local/lib/ruby/gems/3.2.0/gems/rserve-simpler-0.0.6/lib/rserve/simpler.rb:21:in 'block (2 levels) in with'
/usr/local/lib/ruby/gems/3.2.0/gems/rserve-simpler-0.0.6/lib/rserve/simpler.rb:21:in 'map'
/usr/local/lib/ruby/gems/3.2.0/gems/rserve-simpler-0.0.6/lib/rserve/simpler.rb:21:in 'block in with'
/usr/local/lib/ruby/gems/3.2.0/gems/rserve-simpler-0.0.6/lib/rserve/simpler.rb:17:in 'each'
/usr/local/lib/ruby/gems/3.2.0/gems/rserve-simpler-0.0.6/lib/rserve/simpler.rb:17:in 'with'
/usr/local/lib/ruby/gems/3.2.0/gems/rserve-simpler-0.0.6/lib/rserve/simpler.rb:74:in 'command'
/opt/openstudio/server/app/lib/analysis_library/r/lhs.rb:97:in 'samples_from_probability'
/opt/openstudio/server/app/lib/analysis_library/r/lhs.rb:186:in 'block in sample_all_variables'
/usr/local/lib/ruby/gems/3.2.0/gems/mongoid-7.5.4/lib/mongoid/contextual/mongo.rb:779:in 'yield_document'
/usr/local/lib/ruby/gems/3.2.0/gems/mongoid-7.5.4/lib/mongoid/contextual/mongo.rb:153:in 'block in each'
/usr/local/lib/ruby/gems/3.2.0/gems/mongo-2.17.4/lib/mongo/collection/view/iterable.rb:86:in 'block in each'
/usr/local/lib/ruby/gems/3.2.0/gems/mongo-2.17.4/lib/mongo/cursor.rb:169:in 'block in each'
/usr/local/lib/ruby/gems/3.2.0/gems/mongo-2.17.4/lib/mongo/cursor.rb:167:in 'loop'
/usr/local/lib/ruby/gems/3.2.0/gems/mongo-2.17.4/lib/mongo/cursor.rb:167:in 'each'
/usr/local/lib/ruby/gems/3.2.0/gems/mongo-2.17.4/lib/mongo/collection/view/iterable.rb:85:in 'each'
/usr/local/lib/ruby/gems/3.2.0/gems/mongoid-7.5.4/lib/mongoid/contextual/mongo.rb:152:in 'each'
/usr/local/lib/ruby/3.2.0/forwardable.rb:240:in 'each'
/opt/openstudio/server/app/lib/analysis_library/r/lhs.rb:149:in 'sample_all_variables'
/opt/openstudio/server/app/lib/analysis_library/lhs.rb:76:in 'perform'
/opt/openstudio/server/app/jobs/resque_jobs/run_analysis.rb:57:in 'perform'
/usr/local/lib/ruby/gems/3.2.0/gems/resque-2.6.0/lib/resque/job.rb:168:in 'perform'`

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio-server/commit/6248825f97170fd394465372050347d0b27e9b6a

**Comment by brianlball** [comment]
The ruby client gem repo is https://github.com/clbustos/Rserve-Ruby-client
The actual RServe library is https://cran.r-project.org/web/packages/Rserve/index.html and it still has activity https://github.com/s-u/Rserve/commits/master/

**Comment by brianlball** [comment]
reopen if necessary
